[package]
name = "hitz-whp"
description = "Windows Hypervisor Platform backend implementing hitz-hal"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
hitz-hal.workspace = true
windows.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
anyhow.workspace = true
hitz-api.workspace = true
hitz-boot.workspace = true
hitz-devices.workspace = true
hitz-vmm.workspace = true
hitz-daemon.workspace = true
tokio.workspace = true
tempfile = "3"
windows = { workspace = true, features = [
    "Win32_System_Memory",
] }
