[package]
name = "hitz-vmm-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
arbitrary = { version = "1", features = ["derive"] }

[dependencies.hitz-vmm]
path = ".."

[[bin]]
name = "fuzz_serial_buf"
path = "fuzz_targets/fuzz_serial_buf.rs"
test = false
doc = false
bench = false

[workspace]
