[package]
name = "hitz-daemon"
description = "tokio runtime, named pipe server, VM coordinator"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
hitz-api.workspace = true
hitz-hal.workspace = true
hitz-vmm.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
hyper.workspace = true
http-body-util.workspace = true
hyper-util.workspace = true
bytes.workspace = true

[dev-dependencies]
tempfile = "3"
