[package]
name = "hitz-net"
description = "virtio-net + WinTun networking"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
hitz-hal.workspace = true
thiserror.workspace = true
tracing.workspace = true
crossbeam-channel.workspace = true
wintun.workspace = true

[dev-dependencies]
proptest = "1.11.0"
